<?php
return [
    [
        'title' => 'Appartamento 1',
        'description' => 'Questo è un bellissimo appartamento nel centro della città.',
        'address' => 'Via Stendhal, 1, 00144 Roma ',
        'price' => '50',
        'beds' => '2',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 2',
        'description' => 'Appartamento spazioso con una vista panoramica mozzafiato.',
        'address' => 'Via Lambro, 11, 20129 Milano',
        'beds' => '3',
        'price' => '48',

        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 3',
        'description' => 'Appartamento moderno e lussuoso vicino alla spiaggia.',
        'address' => 'Via Carlo Bussola, 155, 80143 Napoli',
        'beds' => '4',
        'price' => '32',

        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 0,
    ],
    [
        'title' => 'Appartamento 4',
        'description' => 'Appartamento accogliente nel quartiere tranquillo.',
        'address' => 'Chiasso dei Baroncelli, P.za della Signoria, 3, 50122 Firenze',
        'beds' => '2',
        'price' => '98',

        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 5',
        'description' => 'Appartamento elegante nel cuore della città.',
        'address' => 'Piazza Solferino, 12, 10121 Torino',
        'beds' => '1',
        'price' => '69',

        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 6',
        'description' => 'Appartamento rustico immerso nella campagna.',
        'address' => 'Via San Mamolo, 2, 40136 Bologna',
        'beds' => '5',
        'price' => '37',

        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 7',
        'description' => 'Appartamento moderno con piscina privata.',
        'address' => 'Corso Sardegna, 165, 16142 Genova',
        'beds' => '3',
        'price' => '47',

        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 0,
    ],
    [
        'title' => 'Appartamento 8',
        'description' => 'Appartamento affacciato sul mare con terrazza panoramica.',
        'address' => 'Piazzetta dei Bianchi, 90133 Palermo',
        'beds' => '2',
        'price' => '30',

        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 0,
    ],
    [
        'title' => 'Appartamento 9',
        'description' => 'Appartamento accogliente vicino alle montagne.',
        'address' => 'Calle Crosera, 3820, 30122 Venezia',
        'beds' => '4',
        'price' => '44',

        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 10',
        'description' => 'Appartamento spazioso con vista sulla città.',
        'address' => 'Via Roveggia, 27, 37135 Verona',
        'beds' => '3',
        'price' => '55',

        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 0,
    ],
];
