<?php
return [
    [
        'title' => 'Appartamento 1',
        'description' => 'Questo è un bellissimo appartamento nel centro della città.',
        'address' => 'Via Roma 123, Città',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'beds' => '2',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 2',
        'description' => 'Appartamento spazioso con una vista panoramica mozzafiato.',
        'address' => 'Via Milano 456, Altra Città',
        'beds' => '3',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 3',
        'description' => 'Appartamento moderno e lussuoso vicino alla spiaggia.',
        'address' => 'Via Napoli 789, Località Balneare',
        'beds' => '4',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 0,
    ],
    [
        'title' => 'Appartamento 4',
        'description' => 'Appartamento accogliente nel quartiere tranquillo.',
        'address' => 'Via Venezia 101, Città',
        'beds' => '2',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 5',
        'description' => 'Appartamento elegante nel cuore della città.',
        'address' => 'Via Firenze 222, Città',
        'beds' => '1',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 6',
        'description' => 'Appartamento rustico immerso nella campagna.',
        'address' => 'Via Toscana 33, Campagna',
        'beds' => '5',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 7',
        'description' => 'Appartamento moderno con piscina privata.',
        'address' => 'Via Palermo 555, Periferia',
        'beds' => '3',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 0,
    ],
    [
        'title' => 'Appartamento 8',
        'description' => 'Appartamento affacciato sul mare con terrazza panoramica.',
        'address' => 'Via Sicilia 777, Località Marina',
        'beds' => '2',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 0,
    ],
    [
        'title' => 'Appartamento 9',
        'description' => 'Appartamento accogliente vicino alle montagne.',
        'address' => 'Via Torino 66, Montagne',
        'beds' => '4',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 1,
    ],
    [
        'title' => 'Appartamento 10',
        'description' => 'Appartamento spazioso con vista sulla città.',
        'address' => 'Via Genova 1234, Città',
        'beds' => '3',
        'longitude' => '123548',
        'latitude' => '123548',
        'image' => 'image',
        'rooms' => '5',
        'bathrooms' => '2',
        'square_meters' => '200',
        'is_visible' => 0,
    ],
];
